export const PROJECTS = [
  {
    title: "sonnetjs/sonnet",
    description: "Sonnetjs is an opinionated frontend framework for crafting web ui",
    primaryLanguage: "TypeScript",
    languageColor: "bg-blue-500",
    stars: "1.2k",
    forks: "89",
    technologies: ["TypeScript", "Vite"],
    githubUrl: "https://github.com/sonnetjs/sonnet",
  },
  {
    title: "shadcn-editor",
    description: "Lexical base rich text editor using shadcn/ui components",
    primaryLanguage: "TypeScript",
    languageColor: "bg-blue-500",
    stars: "745",
    forks: "53",
    technologies: ["React", "Next JS", "Tailwind CSS", "Shadcn"],
    githubUrl: "https://github.com/htmujahid/shadcn-editor",
  },
  {
    title: "supasheet",
    description: "The supabase admin panel you've been waiting for",
    primaryLanguage: "TypeScript",
    languageColor: "bg-blue-500",
    stars: "1",
    forks: "0",
    technologies: ["React", "Next JS", "Tailwind CSS", "Supabase"],
    githubUrl: "https://github.com/htmujahid/supasheet",
  },
  {
    title: "barebone-reactivity",
    description: "Reactivity in Vanilla JS using state and signal",
    primaryLanguage: "TypeScript",
    languageColor: "bg-blue-500",
    stars: "1",
    forks: "0",
    technologies: ["Vanilla JS"],
    githubUrl: "https://github.com/htmujahid/barebone-reactivity",
  },
  {
    title: "cleanough",
    description: "A code-sharing social app where developers collaborate, receive feedback, and improve their code together.",
    primaryLanguage: "TypeScript",
    languageColor: "bg-blue-500",
    stars: "2",
    forks: "0",
    technologies: ["React", "Next JS", "Tailwind CSS", "MongoDB"],
  },
  {
    title: "better-start",
    description: "Low-code admin panels for your next project using React, Shadcn, Tanstack, better-auth and drizzle.",
    primaryLanguage: "TypeScript",
    languageColor: "bg-blue-500",
    stars: "7",
    forks: "0",
    technologies: ["React", "Tanstack", "Better Auth", "Drizzle"],
  },
]